//! Descriptor pool for TF Serving pbtxt parsing.
//!
//! We build a `prost_reflect::DescriptorPool` from the compiled-in
//! `FileDescriptorSet` generated by `tonic_build`.

use prost_reflect::DescriptorPool;

/// Return a descriptor pool containing the TF Serving + TensorFlow protos compiled by this crate.
pub fn descriptor_pool() -> DescriptorPool {
    // `tonic_build` exports a single binary blob with descriptors for all compiled protos.
    // This includes our vendored TF Serving + TensorFlow protos.
    DescriptorPool::decode(include_bytes!(concat!(env!("OUT_DIR"), "/descriptor.bin")) as &[u8])
        .expect("failed to decode FileDescriptorSet for monolith-proto")
}
